# Test conda environments for jumeg

name: "Configure conda"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main_dev" branch
  push:
    branches: [ "main_dev" ]
  pull_request:
    branches: [ "main_dev" ]

jobs:
  setup_conda:
    name: Setup jumeg environment.
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: jumeg
          environment-file: jumeg.yml
          python-version: 3.9
          auto-activate-base: false
      - run: |
          conda info
          conda list
          
      - name: Set BASH_ENV
        run: | 
            echo "set -e" >> $BASH_ENV;
            echo "export DISPLAY=:99" >> $BASH_ENV;
            echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV;
            echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV;
      - name: Spin up Xvfb
        run: |
            /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
      - name: Test example
        run: |
            /usr/bin/env python ./examples/connectivity/plot_brain_connectome.py
